#!/usr/bin/env bash
# Writes RecallCore's Linux test entry point (see RecallCore/Package.swift):
# an XCTMain call listing every `func test…()` in Tests/RecallCoreTests.
set -euo pipefail
dir="$(dirname "$0")/../RecallCore/Tests/RecallCoreTests"
{
    echo "// Generated by ios/scripts/linux-test-main.sh — Linux-only entry point for the"
    echo "// RecallCore tests (excluded from the test target everywhere else)."
    echo "import XCTest"
    echo
    echo "XCTMain(["
    for f in "$dir"/*.swift; do
        [[ "$(basename "$f")" == main.swift ]] && continue
        class=$(grep -oP 'class \K\w+(?=: XCTestCase)' "$f" || true)
        [[ -z "$class" ]] && continue
        echo "    testCase(["
        grep -oP 'func \K(test\w+)(?=\(\))' "$f" | while read -r t; do
            echo "        (\"$t\", $class.$t),"
        done
        echo "    ]),"
    done
    echo "])"
} > "$dir/main.swift"
