// Generated by ios/scripts/linux-test-main.sh — Linux-only entry point for the
// RecallCore tests (excluded from the test target everywhere else).
import XCTest

XCTMain([
    testCase([
        ("testFormatters", RecallCoreTests.testFormatters),
        ("testDayArithmetic", RecallCoreTests.testDayArithmetic),
        ("testRowsInsertGapsOfTwentyMinutesOrMore", RecallCoreTests.testRowsInsertGapsOfTwentyMinutesOrMore),
        ("testNoTrailingGapWhileLiveOrOnPastDays", RecallCoreTests.testNoTrailingGapWhileLiveOrOnPastDays),
        ("testOverlappingEntriesDoNotCreateFalseGaps", RecallCoreTests.testOverlappingEntriesDoNotCreateFalseGaps),
        ("testMidnightCrossingEntryAppearsOnBothDaysClipped", RecallCoreTests.testMidnightCrossingEntryAppearsOnBothDaysClipped),
        ("testStatsCountSessionItemsAndIgnoreBackgroundAttention", RecallCoreTests.testStatsCountSessionItemsAndIgnoreBackgroundAttention),
        ("testRowHeights", RecallCoreTests.testRowHeights),
        ("testRibbonSegmentsSkipUntrackedTime", RecallCoreTests.testRibbonSegmentsSkipUntrackedTime),
        ("testRetimeDeltaSnapsToFiveMinutes", RecallCoreTests.testRetimeDeltaSnapsToFiveMinutes),
        ("testStartBlockEndsLiveAndBumpsFrequent", RecallCoreTests.testStartBlockEndsLiveAndBumpsFrequent),
        ("testSplitSharesItemsAndConsumedTime", RecallCoreTests.testSplitSharesItemsAndConsumedTime),
        ("testRetimeKeepsLengthAndStaysInDayAndPast", RecallCoreTests.testRetimeKeepsLengthAndStaysInDayAndPast),
        ("testBackfillUsesFrequentCategory", RecallCoreTests.testBackfillUsesFrequentCategory),
        ("testPendingExpiresAfterAWeek", RecallCoreTests.testPendingExpiresAfterAWeek),
        ("testSetAttentionMovesMediaCategory", RecallCoreTests.testSetAttentionMovesMediaCategory),
        ("testSeedInvariants", RecallCoreTests.testSeedInvariants),
        ("testSeedAtTwentyPastMidnightHasOnlyTheLiveEntryToday", RecallCoreTests.testSeedAtTwentyPastMidnightHasOnlyTheLiveEntryToday),
        ("testClearSamplesKeepsWhatTheUserLogged", RecallCoreTests.testClearSamplesKeepsWhatTheUserLogged),
        ("testOnThisDaySentence", RecallCoreTests.testOnThisDaySentence),
        ("testTopFrequentsPreferTheCurrentHour", RecallCoreTests.testTopFrequentsPreferTheCurrentHour),
        ("testAutocompleteAndSearch", RecallCoreTests.testAutocompleteAndSearch),
        ("testWeekInsights", RecallCoreTests.testWeekInsights),
        ("testMonthGridIsMondayFirst", RecallCoreTests.testMonthGridIsMondayFirst),
        ("testHeatmapFillUsesHistoryThenDetail", RecallCoreTests.testHeatmapFillUsesHistoryThenDetail),
        ("testSourceDetection", RecallCoreTests.testSourceDetection),
        ("testAutoIngestMakesSamplePendingEntriesInThePast", RecallCoreTests.testAutoIngestMakesSamplePendingEntriesInThePast),
        ("testSharedMediaIsBackdatedByItsLength", RecallCoreTests.testSharedMediaIsBackdatedByItsLength),
        ("testISO8601", RecallCoreTests.testISO8601),
        ("testSnapshotRoundTripAndLenientDecoding", RecallCoreTests.testSnapshotRoundTripAndLenientDecoding),
    ]),
])
